---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: cache
  namespace: default
  labels:
    chart: redis
spec:
  chartGitPath: redis
  releaseName: cache
  values:
    image: bitnami/redis:4.0.9
    maxmemory: 128mb
    eviction: allkeys-lru
