---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: frontend
  namespace: default
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  releaseName: frontend
  values:
    replicaCount: 2
    backend: http://backend-podinfo:9898/echo
    image:
      tag: 0.2.2
    service:
      type: NodePort
      nodePort: 31198
